name: CI

on:
  pull_request:
    branches:
      - dev
      - master
  push:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn

      - run: yarn prettier:check

      - run: yarn test --coverage --watchAll=false

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v1
        with:
          path: coverage
          name: code-coverage

      - name: Build Project
        if: github.event_name == 'push'
        run: yarn run build

      - name: Upload Build Folder
        uses: actions/upload-artifact@v1
        if: github.event_name == 'push'
        with:
          path: build
          name: build

      - name: Create a Release
        run: yarn semantic-release
        if: github.event_name == 'push' && github.ref == "refs/heads/master"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain curvy-butter.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
