name: CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn

      - run: yarn prettier:check

      - run: yarn test --coverage --watchAll=false

      - name: Build Project
        if: github.event_name == 'push'
        run: yarn run build

      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain curvy-butter.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
